# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7r9GnxE1Al-FHvgnMAHxDuPWiu7q1f5
"""

# File: models/embeddings.py

from sentence_transformers import SentenceTransformer

class GuardianEmbeddings:
    """
    A class to handle the Sentence-Transformer embedding model.
    """
    def __init__(self, model_name="all-MiniLM-L6-v2"):
        """
        Initializes the embedding model.

        Args:
            model_name (str): The name of the pre-trained model to use.
                              "all-MiniLM-L6-v2" is a good, lightweight choice.
        """
        try:
            self.model = SentenceTransformer(model_name)
            print(f"Embedding model '{model_name}' loaded successfully.")
        except Exception as e:
            print(f"Error loading the embedding model: {e}")
            print("Please ensure you have installed the required libraries.")
            print("Run the following command in your terminal:")
            print("pip install sentence-transformers")


    def embed_text(self, text_list):
        """
        Generates embeddings for a list of text strings.

        Args:
            text_list (list of str): A list of text chunks.

        Returns:
            A list of embeddings (numpy array).
        """
        return self.model.encode(text_list, convert_to_numpy=True)

